### ISSUE TITLE
"Project maintainers" link in elections is broken

### ISSUE THREAD

**Issue by azbarcea** [voxpupuli/voxpupuli.github.io#194]
Going on https://voxpupuli.org/elections/, the link leads to a 404 error at https://github.com/orgs/voxpupuli/teams/project-maintainers:
> The current list of PMC members can be found on [GitHub](https://github.com/orgs/voxpupuli/teams/project-maintainers/members).

----
See also ["Project maintainers" link in COC is broken](#59)

**Comment by ghoneycutt** [comment]
I clicked all the links and could not duplicate this. Could you be more specific.

**Comment by ghoneycutt** [comment]
Am not able to confirm. Went through each link (and re-ordered them)

https://github.com/voxpupuli/voxpupuli.github.io/pull/198

**Comment by azbarcea** [comment]
That's probably because you're already logged-in into Github and you have access to the organization team details: https://github.com/orgs/voxpupuli/teams/project-maintainers

The above link is not public, nor somebody outside of the organization can access. The public link is: https://github.com/orgs/voxpupuli/people

**Comment by bastelfreak** [comment]
@azbarcea as a short-term workaround, I created https://github.com/voxpupuli/voxpupuli.github.io/pull/201. Our original goal was to not duplicate the list of people. This is always annoying after elections because it needs to be updated at multiple places. I've no proper alternative at the moment, but the new text at least explains it.
